import type { ContentWidgetDefinition } from './content-widget-types'

export const contentWidgetDefinitions: ContentWidgetDefinition[] = [
  {
    id: 'alert',
    title: '提示框',
    description: '带状态图标和标题的内容提示。',
    category: '提示',
    kind: 'block',
    tagName: 'xhhao-com-alert',
    attributes: { type: 'tip', title: '提醒' },
    innerHTML: '这里写提示内容。',
    keywords: ['alert', 'tip', 'info', 'warning'],
  },
  {
    id: 'tip',
    title: '悬浮提示',
    description: '鼠标悬浮时显示补充说明。',
    category: '提示',
    kind: 'inline',
    tagName: 'xhhao-com-tip',
    attributes: { tip: '这里是提示内容' },
    innerHTML: '提示文本',
    keywords: ['tip', 'tooltip'],
  },
  {
    id: 'quote',
    title: '引用',
    description: '用于醒目展示引用或摘录。',
    category: '提示',
    kind: 'block',
    tagName: 'xhhao-com-quote',
    innerHTML: '保持清醒，保持热爱。',
    keywords: ['quote'],
  },
  {
    id: 'note',
    title: '便签',
    description: '纸条式重点记录。',
    category: '提示',
    kind: 'block',
    tagName: 'xhhao-com-note',
    attributes: { color: 'yellow' },
    innerHTML: '这里写便签内容。',
    keywords: ['note'],
  },
  {
    id: 'result',
    title: '结果',
    description: '展示操作结果或阶段结论。',
    category: '提示',
    kind: 'block',
    tagName: 'xhhao-com-result',
    attributes: { type: 'success', title: '完成' },
    innerHTML: '这里写结果说明。',
    keywords: ['result', 'success'],
  },
  {
    id: 'tab',
    title: '标签页',
    description: '将内容切分到多个页签中。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-tab',
    attributes: { tabs: '介绍,示例', active: '1' },
    innerHTML:
      '<xhhao-com-tab-panel>这里写第一个标签页内容。</xhhao-com-tab-panel><xhhao-com-tab-panel>这里写第二个标签页内容。</xhhao-com-tab-panel>',
    keywords: ['tab', 'tabs'],
  },
  {
    id: 'folding',
    title: '折叠面板',
    description: '默认收起一段补充内容。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-folding',
    attributes: { title: '展开查看更多' },
    innerHTML: '这里写折叠内容。',
    keywords: ['folding', 'details'],
  },
  {
    id: 'split',
    title: '分栏',
    description: '把内容横向拆成多个栏。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-split',
    attributes: { cols: '2', gap: '1rem' },
    innerHTML: '<div>左侧内容</div><div>右侧内容</div>',
    keywords: ['split', 'columns'],
  },
  {
    id: 'stepper',
    title: '步骤',
    description: '展示流程步骤。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-stepper',
    innerHTML:
      '<xhhao-com-step title="第一步">说明第一步要做什么。</xhhao-com-step><xhhao-com-step title="第二步">说明第二步要做什么。</xhhao-com-step>',
    keywords: ['stepper', 'steps'],
  },
  {
    id: 'timeline',
    title: '时间线',
    description: '按时间顺序展示事件。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-timeline',
    innerHTML:
      '<xhhao-com-timeline-item time="09:00">开始准备。</xhhao-com-timeline-item><xhhao-com-timeline-item time="10:30">完成关键节点。</xhhao-com-timeline-item>',
    keywords: ['timeline'],
  },
  {
    id: 'card-list',
    title: '卡片列表',
    description: '把列表内容呈现为卡片网格。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-card-list',
    innerHTML: '<ul><li>卡片一</li><li>卡片二</li><li>卡片三</li></ul>',
    keywords: ['card', 'list'],
  },
  {
    id: 'compare',
    title: '对比',
    description: '并排展示前后或左右内容。',
    category: '布局',
    kind: 'block',
    tagName: 'xhhao-com-compare',
    attributes: {
      'left-title': '之前',
      'right-title': '之后',
      left: '之前的内容',
      right: '之后的内容',
    },
    keywords: ['compare'],
  },
  {
    id: 'copy',
    title: '复制命令',
    description: '可一键复制的命令行片段。',
    category: '代码',
    kind: 'block',
    tagName: 'xhhao-com-copy',
    attributes: { prompt: '$' },
    innerHTML: 'pnpm install',
    keywords: ['copy', 'code'],
  },
  {
    id: 'command-group',
    title: '命令组',
    description: '展示多条命令并支持整体复制。',
    category: '代码',
    kind: 'block',
    tagName: 'xhhao-com-command-group',
    attributes: { title: '部署命令' },
    innerHTML:
      '<xhhao-com-command prompt="$">pnpm install</xhhao-com-command><xhhao-com-command prompt="$">pnpm build</xhhao-com-command>',
    keywords: ['command', 'terminal'],
  },
  {
    id: 'key',
    title: '快捷键',
    description: '展示键盘按键或组合键。',
    category: '代码',
    kind: 'inline',
    tagName: 'xhhao-com-key',
    attributes: { cmd: 'true', code: 'K' },
    keywords: ['key', 'keyboard'],
  },
  {
    id: 'chat',
    title: '聊天',
    description: 'QQ 风格对话内容。',
    category: '展示',
    kind: 'block',
    tagName: 'xhhao-com-chat',
    innerHTML:
      '<xhhao-com-chat-item name="小明" avatar="">你好呀。</xhhao-com-chat-item><xhhao-com-chat-item name="我" self>欢迎使用文章组件。</xhhao-com-chat-item>',
    keywords: ['chat'],
  },
  {
    id: 'pic',
    title: '图片',
    description: '带说明文字的图片。',
    category: '展示',
    kind: 'block',
    tagName: 'xhhao-com-pic',
    attributes: { src: 'https://picsum.photos/960/540', caption: '图片说明' },
    keywords: ['pic', 'image'],
  },
  {
    id: 'progress',
    title: '进度条',
    description: '展示百分比或任务进度。',
    category: '展示',
    kind: 'block',
    tagName: 'xhhao-com-progress',
    attributes: { value: '70', max: '100', label: '进度' },
    keywords: ['progress'],
  },
  {
    id: 'status',
    title: '状态',
    description: '展示轻量状态值。',
    category: '展示',
    kind: 'inline',
    tagName: 'xhhao-com-status',
    attributes: { label: '状态', type: 'success' },
    innerHTML: '正常',
    keywords: ['status'],
  },
  {
    id: 'badge',
    title: '徽标',
    description: '行内短标签。',
    category: '展示',
    kind: 'inline',
    tagName: 'xhhao-com-badge',
    attributes: { type: 'info' },
    innerHTML: 'Beta',
    keywords: ['badge'],
  },
  {
    id: 'button',
    title: '按钮',
    description: '行内按钮链接。',
    category: '展示',
    kind: 'inline',
    tagName: 'xhhao-com-button',
    attributes: { href: 'https://www.xhhao.com', target: '_blank' },
    innerHTML: '访问链接',
    keywords: ['button', 'link'],
  },
  {
    id: 'task-list',
    title: '任务清单',
    description: '展示已完成和待完成事项。',
    category: '展示',
    kind: 'block',
    tagName: 'xhhao-com-task-list',
    innerHTML:
      '<xhhao-com-task checked>已完成事项</xhhao-com-task><xhhao-com-task>待完成事项</xhhao-com-task>',
    keywords: ['task', 'todo'],
  },
  {
    id: 'emoji-clock',
    title: '表情时钟',
    description: '显示随时间变化的时钟表情。',
    category: '行内',
    kind: 'inline',
    tagName: 'xhhao-com-emoji-clock',
    keywords: ['emoji', 'clock'],
  },
  {
    id: 'blur',
    title: '模糊文本',
    description: '鼠标悬浮后显示隐藏内容。',
    category: '行内',
    kind: 'inline',
    tagName: 'xhhao-com-blur',
    innerHTML: '隐藏内容',
    keywords: ['blur'],
  },
  {
    id: 'annotation',
    title: '批注',
    description: '给行内文本加小注释。',
    category: '行内',
    kind: 'inline',
    tagName: 'xhhao-com-annotation',
    attributes: { note: '说明' },
    innerHTML: '需要批注的文本',
    keywords: ['annotation'],
  },
  {
    id: 'reading-time',
    title: '阅读时间',
    description: '展示估算阅读时间。',
    category: '行内',
    kind: 'inline',
    tagName: 'xhhao-com-reading-time',
    attributes: { words: '1200' },
    keywords: ['reading', 'time'],
  },
]

export const contentWidgetCategories = Array.from(
  new Set(contentWidgetDefinitions.map((item) => item.category)),
)

export const blockWidgetTags = contentWidgetDefinitions
  .filter((item) => item.kind === 'block')
  .map((item) => item.tagName)

export const inlineWidgetTags = contentWidgetDefinitions
  .filter((item) => item.kind === 'inline')
  .map((item) => item.tagName)

export function getContentWidgetDefinitionByTagName(tagName: string) {
  return contentWidgetDefinitions.find((item) => item.tagName === tagName)
}
